name: "Replace web.config variables"
description: "Replace variables in web.config using environment and Key Vault secrets file"
inputs:
  environment:
    description: "Environment name (e.g. smoke, staging, production)"
    required: true
  keyvault-name:
    description: "Azure Key Vault name"
    required: true
  file-path:
    description: "Path to the web.config file"
    required: true
  secrets-env-path:
    description: "Path to the secrets.env file (default: ./secrets.env)"
    required: false
    default: "./secrets.env"
  replace-script-path:
    description: "Path to replace.sh script"
    required: false
    default: "./replace.sh"
  use-keyvault:
    description: "Flag to determine if Key Vault should be used"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Replace variables in web.config
      shell: bash
      run: |
        echo "Replacing variables in web.config..."
        echo "Environment: ${{ inputs.environment }}"
        echo "Key Vault Name: ${{ inputs.keyvault-name }}"
        echo "File Path: ${{ inputs.file-path }}"
        echo "Secrets Env Path: ${{ inputs.secrets-env-path }}"
        echo "Replace Script Path: ${{ inputs.replace-script-path }}"
        echo "Use Key Vault: ${{ inputs.use-keyvault }}"
        echo "Running replace.sh script..."

        chmod +x "${{ inputs.replace-script-path }}"
        "${{ inputs.replace-script-path }}" \
          "${{ inputs.file-path }}" 
