name: "Replace web.config variables"
description: "Replace variables in web.config using environment and Key Vault secrets file"
inputs:
  environment:
    description: "Environment name (e.g. smoke, staging, production)"
    required: true
  keyvault-name:
    description: "Azure Key Vault name"
    required: true
  file-path:
    description: "Path to the web.config file"
    required: true
  secrets-env-path:
    description: "Path to the secrets.env file (default: ./secrets.env)"
    required: false
    default: "./secrets.env"
  replace-script-path:
    description: "Path to replace.sh script"
    required: false
    default: "./replace.sh"

runs:
  using: "composite"
  steps:
    - name: Replace variables in web.config
      shell: bash
      run: |
        chmod +x "${{ inputs.replace-script-path }}"
        "${{ inputs.replace-script-path }}" \
          "${{ inputs.environment }}" \
          "${{ inputs.keyvault-name }}" \
          "${{ inputs.file-path }}" \
          "${{ inputs.secrets-env-path }}"
