name: Create Empty GitHub Repository

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'Repository owner (optional)'
        required: false
        default: ''
      repo_name:
        description: 'Repository name'
        required: true
      visibility:
        description: 'Repository visibility (public or private)'
        required: true
        default: 'public'
      description:
        description: 'Repository description (optional)'
        required: false
        default: ''

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create Empty GitHub Repository
        uses: ./.github/actions/create-empty-repo
        with:
          owner: ${{ github.event.inputs.owner }}
          repo_name: ${{ github.event.inputs.repo_name }}
          visibility: ${{ github.event.inputs.visibility }}
          description: ${{ github.event.inputs.description }}
          gh_token: ${{ secrets.GH_PAT }}