name: Import Repository

on:
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  import-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Send Import Request
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          VCS_URL: "https://thienthutula1109.visualstudio.com/phongmx/_git/First%20Repo"
          OWNER: "xuanphongit"
          REPO_NAME: "phongmxgithub"
          VISIBILITY: "public"
          SOURCE_USERNAME: "xuanphongit1109@gmail.com"
          SOURCE_ACCESS_TOKEN: "xuanphongit1109@" # Lưu ý: Lưu token này trong Secrets
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: text/html" \
            -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryhhTR4q2J1ocmCTgj" \
            -H "github-verified-fetch: true" \
            --data-binary $'------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="vcs_url"\r\n\r\n${VCS_URL}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="owner"\r\n\r\n${OWNER}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="repository[name]"\r\n\r\n${REPO_NAME}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="repository[visibility]"\r\n\r\n${VISIBILITY}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="source_username"\r\n\r\n${SOURCE_USERNAME}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj\r\nContent-Disposition: form-data; name="source_access_token"\r\n\r\n${SOURCE_ACCESS_TOKEN}\r\n------WebKitFormBoundaryhhTR4q2J1ocmCTgj--\r\n' \
            https://github.com/new/import