name: Load Environment Variables

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Comma-separated list of environments to load (e.g. smoke,smoke2,smoke3,smoke4,smoke5)'
        required: true
        default: 'smoke,smoke2,smoke3,smoke4,smoke5'

jobs:
  load-variables:
    runs-on: windows-latest
    strategy:
      matrix:
        environment: ['smoke', 'smoke2', 'smoke3', 'smoke4', 'smoke5']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export variables from environment
        shell: pwsh
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          Write-Host "Exporting variables from ${{ matrix.environment }} environment..."
          $vars = $env:VARS_CONTEXT | ConvertFrom-Json
          $vars.PSObject.Properties | ForEach-Object {
            $key = "${{ matrix.environment }}_$($_.Name)"
            $value = $_.Value
            echo "$key=$value" >> $env:GITHUB_ENV
            Write-Host "Exported $key"
          }

      - name: Save variables to file
        shell: pwsh
        run: |
          # Create empty file first
          New-Item -Path "${{ matrix.environment }}_vars.txt" -ItemType File -Force
          
          # Get all variables with environment prefix and save to file
          Get-ChildItem env: | Where-Object { $_.Name -like "${{ matrix.environment }}_*" } | ForEach-Object {
            "$($_.Name)=$($_.Value)" | Out-File -FilePath "${{ matrix.environment }}_vars.txt" -Append
            Write-Host "Saved $($_.Name)"
          }

          # Verify file exists and has content
          if (Test-Path "${{ matrix.environment }}_vars.txt") {
            $content = Get-Content "${{ matrix.environment }}_vars.txt"
            Write-Host "File contains $($content.Count) variables"
            if ($content.Count -eq 0) {
              Write-Host "Warning: No variables were found for ${{ matrix.environment }}"
              # Add a dummy variable to ensure file is not empty
              "NO_VARIABLES_FOUND=true" | Out-File -FilePath "${{ matrix.environment }}_vars.txt" -Append
            }
          } else {
            Write-Host "Error: Failed to create ${{ matrix.environment }}_vars.txt"
            exit 1
          }

      - name: Upload variables
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}-variables
          path: ${{ matrix.environment }}_vars.txt

  merge-and-update:
    runs-on: windows-latest
    needs: load-variables
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download smoke variables
        uses: actions/download-artifact@v4
        with:
          name: smoke-variables
          path: smoke_vars

      - name: Download smoke2 variables
        uses: actions/download-artifact@v4
        with:
          name: smoke2-variables
          path: smoke2_vars

      - name: Download smoke3 variables
        uses: actions/download-artifact@v4
        with:
          name: smoke3-variables
          path: smoke3_vars

      - name: Download smoke4 variables
        uses: actions/download-artifact@v4
        with:
          name: smoke4-variables
          path: smoke4_vars

      - name: Download smoke5 variables
        uses: actions/download-artifact@v4
        with:
          name: smoke5-variables
          path: smoke5_vars

      - name: Merge variables to GITHUB_ENV
        shell: pwsh
        run: |
          $environments = @('smoke', 'smoke2', 'smoke3', 'smoke4', 'smoke5')
          $mergedVars = @{}
          
          # Read and merge all variables
          foreach ($env in $environments) {
            Write-Host "Reading variables from $env"
            if (Test-Path "$env`_vars/$env`_vars.txt") {
              Get-Content "$env`_vars/$env`_vars.txt" | ForEach-Object {
                if ($_ -match "(.+?)=(.+)") {
                  $key = $matches[1]
                  $value = $matches[2]
                  $mergedVars[$key] = $value
                  # Export to GITHUB_ENV
                  echo "$key=$value" >> $env:GITHUB_ENV
                  Write-Host "Exported to GITHUB_ENV: $key"
                }
              }
            } else {
              Write-Host "Warning: $env`_vars/$env`_vars.txt not found"
            }
          }
          
          # Save merged variables to a file for reference
          $mergedVars.GetEnumerator() | ForEach-Object {
            "$($_.Key)=$($_.Value)" | Out-File -FilePath "merged_vars.txt" -Append
          }
          Write-Host "All variables have been merged and exported to GITHUB_ENV"

      - name: Update web.config
        shell: pwsh
        run: |
          # Check if web.config exists
          if (Test-Path "web.config") {
            # Create a backup of web.config
            Copy-Item "web.config" "web.config.backup"
            
            # Read the current web.config content
            $webConfig = Get-Content "web.config" -Raw
            
            # Update web.config with merged variables
            Get-Content "merged_vars.txt" | ForEach-Object {
              if ($_ -match "(.+?)=(.+)") {
                $key = $matches[1]
                $value = $matches[2] -replace '([\/&])', '\$1'
                $pattern = "<add key=`"$key`".*?\/>"
                $replacement = "<add key=`"$key`" value=`"$value`"\/>"
                $webConfig = $webConfig -replace $pattern, $replacement
              }
            }
            
            # Save the updated content back to web.config
            $webConfig | Set-Content "web.config"
            Write-Host "web.config has been updated with merged variables"
          } else {
            Write-Host "web.config not found"
            exit 1
          }

      - name: Show updated web.config
        shell: pwsh
        run: |
          if (Test-Path "web.config") {
            Get-Content "web.config"
          }

      - name: Show merged variables
        shell: pwsh
        run: |
          if (Test-Path "merged_vars.txt") {
            Write-Host "Merged variables:"
            Get-Content "merged_vars.txt"
          } 