name: Mirror ADO Repo to GitHub

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repo (GitHub)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git Credentials and Configuration
        run: |
          git config --global user.name 'GitHub Actions Mirror'
          git config --global user.email 'actions-mirror@github.com'

      - name: Install gh CLI and git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install gh git-lfs -y
          git lfs install

      - name: Check if GitHub repo exists, create if not
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          set -e
          if ! gh repo view <GITHUB_OWNER>/<GITHUB_REPO> > /dev/null 2>&1; then
            echo "Repo does not exist. Creating..."
            gh repo create <GITHUB_OWNER>/<GITHUB_REPO> --public --confirm
          else
            echo "Repo already exists."
          fi

      - name: Add ADO remote and fetch
        env:
          ADO_REPO_URL: "https://dev.azure.com/<ADO_ORG_NAME>/<ADO_PROJECT_NAME>/_git/<ADO_REPO_NAME>"
          ADO_PAT: ${{ secrets.ADO_PAT }}
        run: |
          set -e
          git remote add --tags ado_mirror "https://PAT:${ADO_PAT}@${ADO_REPO_URL#https://}"
          git fetch ado_mirror --prune --tags --force

      - name: Check for files >100MB in ADO repo
        id: lfs_check
        run: |
          set -e
          git checkout ado_mirror/main || git checkout ado_mirror/master
          large_files=$(git ls-tree -r -l HEAD | awk '$4 > 104857600 {print $5}')
          if [ -n "$large_files" ]; then
            echo "LFS_NEEDED=true" >> $GITHUB_OUTPUT
            echo "Large files detected:"
            echo "$large_files"
            # Add all large files to LFS, regardless of extension
            for file in $large_files; do
              path=$(git ls-tree -r -l HEAD | awk -v f="$file" '$5 == f {print $NF}')
              if [ -n "$path" ]; then
                git lfs track "$path"
              fi
            done
            git add .gitattributes
            git commit -m "Track all files >100MB with Git LFS" || true
          else
            echo "LFS_NEEDED=false" >> $GITHUB_OUTPUT
          fi

      - name: Apply Git LFS and rewrite history if needed
        if: steps.lfs_check.outputs.LFS_NEEDED == 'true'
        run: |
          set -e
          git lfs install
          # Rewrite history to move large files to LFS
          npx git-filter-repo --replace-text <(git lfs migrate info --everything | grep 'oid sha256:' | awk '{print $3}' | xargs -I{} echo '{}==>lfs')
          git lfs push --all origin

      - name: Mirror to GitHub origin
        run: |
          set -e
          git remote set-url origin "https://x-access-token:${{ secrets.GH_PAT }}@github.com/<GITHUB_OWNER>/<GITHUB_REPO>.git"
          git push origin --mirror