name: Get conffig from Key Vault and replace in web.config
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ApiEndpoint: https://env-api.override.com

    steps:
    - uses: actions/checkout@v4  # ⬅️ Latest checkout action!

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download secrets from Key Vault
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo "Fetching secrets from Key Vault..."
          secrets=$(az keyvault secret list --vault-name "my-keyvault-phongmx" --query "[].id" -o tsv)

          if [ -z "$secrets" ]; then
            echo "No secrets found in Key Vault."
            exit 1
          fi

          > "./secrets.env"

          for secret_id in $secrets; do
            name=$(basename "$secret_id")
            value=$(az keyvault secret show --id "$secret_id" --query "value" -o tsv)
            echo "$name=\"$value\"" >> "./secrets.env"
          done

    - name: Replace configs
      uses: ./.github/actions/replace-webconfig
      with:
        environment: smoke
        keyvault-name: my-keyvault-phongmx
        file-path: ./my-app/web.config
        secrets-env-path: ./secrets.env
        replace-script-path: ./replace.sh