name: Get config from Key Vault and replace in web.config
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      use-keyvault:
        description: 'Use Azure Key Vault'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      if: ${{ inputs.use-keyvault == 'true' }}
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download secrets from Key Vault
      if: ${{ inputs.use-keyvault == 'true' }}
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo "Fetching secrets from Key Vault..."
          secrets=$(az keyvault secret list --vault-name "my-keyvault-phongmx" --query "[].id" -o tsv)

          if [ -z "$secrets" ]; then
            echo "No secrets found in Key Vault."
            exit 1
          fi

          > "./secrets.env"

          for secret_id in $secrets; do
            name=$(basename "$secret_id")
            value=$(az keyvault secret show --id "$secret_id" --query "value" -o tsv)
            echo "$name=\"$value\"" >> "./secrets.env"
          done

    - name: Replace configs
      uses: ./.github/actions/replace-webconfig
      with:
        environment: smoke
        keyvault-name: my-keyvault-phongmx
        file-path: ./my-app/web.config
        secrets-env-path: ./secrets.env
        replace-script-path: ./replace.sh
        use-keyvault: ${{ inputs.use-keyvault }}