name: Load Smoke Variables and Replace Placeholders in web.config

on:
  workflow_dispatch: # Manual trigger; adjust as needed (e.g., push, pull_request)

jobs:
  load-smoke-vars:
    runs-on: ubuntu-latest
    environment: smoke # Specify the smoke environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Export variables from smoke environment
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "Exporting variables from smoke environment..."
          echo "$VARS_CONTEXT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Run replace.sh
        run: |
          chmod +x replace.sh
          ./replace.sh web.config