name: Load Smoke Variables and Replace Placeholders in web.config

on:
  workflow_dispatch: # Manual trigger; adjust as needed (e.g., push, pull_request)

jobs:
  load-smoke-vars:
    runs-on: ubuntu-latest
    environment: smoke # Specify the smoke environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Export variables from smoke environment
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "Exporting variables from smoke environment..."
          echo "$VARS_CONTEXT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Azure Login
        if: ${{ inputs.use-keyvault == 'true' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Read all secrets from Azure Key Vault
        uses: azure/CLI@v2
        with:
          inlineScript: |
              echo "Listing all secrets in Key Vault..."
              secrets=$(az keyvault secret list \
                --vault-name "my-keyvault-phongmx" \
                --query "[].name" \
                --output tsv)
              if [ -z "$secrets" ]; then
                echo "Warning: No secrets found in Key Vault."
              else
                for secret in $secrets; do
                  echo "Reading secret $secret from Key Vault..."
                  value=$(az keyvault secret show \
                    --vault-name "my-keyvault-phongmx" \
                    --name "$secret" \
                    --query "value" \
                    --output tsv || echo "Failed to read secret $secret")
                  if [ -n "$value" ]; then
                    # Convert secret name to uppercase for consistency
                    upper_secret="${secret^^}"
                    echo "$upper_secret=$value" >> $GITHUB_ENV
                  else
                    echo "Warning: Secret $secret is empty or inaccessible."
                  fi
                done
              fi

      - name: Run replace.sh
        run: |
          chmod +x replace.sh
          ./replace.sh web.config